# This file provides instructions for packaging.

`MooseX-DeclareX-Keyword-interface`
	perl_version_from m`MooseX::DeclareX::Keyword::interface`;
	version_from      m`MooseX::DeclareX::Keyword::interface`;
	readme_from       m`MooseX::DeclareX::Keyword::interface`;
	requires          p`MooseX::Interface 0.002`;
	requires          p`MooseX::DeclareX 0.002`;
	test_requires     p`Test::More 0.61`.

